I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 77, in script
    scene home bg
Exception: Image 'home' does not accept attributes 'bg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 77, in script
    scene home bg
  File "C:\Users\Maidy Putri Joshi\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 1247, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Maidy Putri Joshi\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Maidy Putri Joshi\Downloads\renpy-8.2.1-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Maidy Putri Joshi\Downloads\renpy-8.2.1-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Maidy Putri Joshi\Downloads\renpy-8.2.1-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\Maidy Putri Joshi\Downloads\renpy-8.2.1-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'home' does not accept attributes 'bg'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Maxy VN 1.0
Fri Apr 19 13:23:05 2024
